import Head from 'next/head'
import Image from 'next/image'
import Todos from '../components/Todos'
import { useAuthContext } from '../context/AuthContext'
import styles from '../styles/Home.module.css'

export default function Home() {

  const { user } = useAuthContext();

  return (
    <div>
      <Head>
        <title>Talexy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        { user ? (
          <Todos />
        ) : (
          <h1>ログインしよう</h1>
        ) }
      </div>
    </div>
  )
}
